### ISSUE TITLE
프로젝트 방향 아이템1

### ISSUE THREAD

**Issue by kangdain** [kangdain/TLO#2]
# 암호화폐 거래

- 코인 이름
- 시가총액
- 코인 공급량
- 시가총액 
- 변동 
등의 데이터를 크롤링 하여 실시간 확인

**Comment by unizard** [comment]
@kangdain 금융분야도 매우 핫 한 분야이긴 하지만, 인공지능의 금융의 만남의 융합 영역이 진입장벽이 좀 있으니 좀더 다양하게 생각해보도록 하죠. 이슈로 3~4개 더 정리해서 쭉 달아주세요.

**Comment by unizard** [comment]
해당 프로젝트 시작시 다시 Open 합니다.
